import ToeplitzPositroids.RankThree.OneSidedAssembly
import ToeplitzPositroids.RankThree.EndpointParallel
import Mathlib.Tactic

/-!
# Raw one-sided endpoint constructions

This file develops the remaining support-boundary recurrence used when an
initial loop block is present. Its initial ratios are `0,0,ε`; all later
ratios are generated by the same finite-slope recurrence.
-/

namespace ToeplitzPositroids.RankThree

open ToeplitzPositroids

noncomputable section

/-- The ratio sequence at a left coefficient-support boundary. -/
def boundarySynthesizedRatio {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) : ℕ → ℝ
  | 0 => 0
  | 1 => 0
  | 2 => ε
  | j + 3 => nextSynthesizedRatio (boundarySynthesizedRatio s ε (j + 1))
      (boundarySynthesizedRatio s ε (j + 2)) (finiteSlopeValue s j)

@[simp] theorem boundarySynthesizedRatio_zero {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) :
    boundarySynthesizedRatio s ε 0 = 0 := rfl

@[simp] theorem boundarySynthesizedRatio_one {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) :
    boundarySynthesizedRatio s ε 1 = 0 := rfl

@[simp] theorem boundarySynthesizedRatio_two {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) :
    boundarySynthesizedRatio s ε 2 = ε := rfl

@[simp] theorem boundarySynthesizedRatio_add_three {N : ℕ} (s : Fin N → ℝ) (ε : ℝ)
    (j : ℕ) :
    boundarySynthesizedRatio s ε (j + 3) =
      nextSynthesizedRatio (boundarySynthesizedRatio s ε (j + 1))
        (boundarySynthesizedRatio s ε (j + 2)) (finiteSlopeValue s j) := rfl

/-- The cancellation-friendly recurrence increment at a boundary. -/
theorem boundarySynthesizedRatio_increment {N : ℕ} (s : Fin N → ℝ) (ε : ℝ)
    {j : ℕ} (hj : j < N) :
    boundarySynthesizedRatio s ε (j + 3) - boundarySynthesizedRatio s ε (j + 2) =
      boundarySynthesizedRatio s ε (j + 2) *
        (boundarySynthesizedRatio s ε (j + 2) - boundarySynthesizedRatio s ε (j + 1)) /
          (s ⟨j, hj⟩ - boundarySynthesizedRatio s ε (j + 2)) := by
  rw [boundarySynthesizedRatio_add_three, finiteSlopeValue_apply s hj]
  simp only [nextSynthesizedRatio]
  ring

/-- The boundary recurrence has positive decreasing increments and an explicit linear bound. -/
theorem boundarySynthesizedRatio_invariants {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) :
    ∀ k : ℕ, k ≤ N →
      0 ≤ boundarySynthesizedRatio s ε (k + 1) ∧
        0 < boundarySynthesizedRatio s ε (k + 2) ∧
        0 < boundarySynthesizedRatio s ε (k + 2) - boundarySynthesizedRatio s ε (k + 1) ∧
        boundarySynthesizedRatio s ε (k + 2) - boundarySynthesizedRatio s ε (k + 1) ≤ ε ∧
        boundarySynthesizedRatio s ε (k + 2) ≤ (k + 1 : ℝ) * ε := by
  intro k hk
  induction k with
  | zero =>
      simp only [boundarySynthesizedRatio_one, boundarySynthesizedRatio_two, Nat.cast_zero,
        zero_add]
      refine ⟨le_rfl, hε.1, ?_, ?_, ?_⟩
      · simpa using hε.1
      · simp
      · norm_num
  | succ k ih =>
      have hkN : k < N := by omega
      obtain ⟨hprevNonneg, hcurPos, hΔPos, hΔLe, hcurBound⟩ := ih (by omega)
      have hkBound : (k + 1 : ℝ) ≤ (N + 2 : ℝ) := by
        exact_mod_cast (show k + 1 ≤ N + 2 by omega)
      have hglobalBound : boundarySynthesizedRatio s ε (k + 2) ≤
          (N + 2 : ℝ) * ε :=
        hcurBound.trans (mul_le_mul_of_nonneg_right hkBound hε.1.le)
      have hsmall := hε.2 ⟨k, hkN⟩
      have htwocur : 2 * boundarySynthesizedRatio s ε (k + 2) < s ⟨k, hkN⟩ := by
        nlinarith
      have hdenPos : 0 < s ⟨k, hkN⟩ - boundarySynthesizedRatio s ε (k + 2) := by
        linarith
      have hfactorLe : boundarySynthesizedRatio s ε (k + 2) /
          (s ⟨k, hkN⟩ - boundarySynthesizedRatio s ε (k + 2)) ≤ 1 := by
        rw [div_le_one hdenPos]
        linarith
      have hinc := boundarySynthesizedRatio_increment s ε hkN
      have hnextPos : 0 < boundarySynthesizedRatio s ε (k + 3) -
          boundarySynthesizedRatio s ε (k + 2) := by
        rw [hinc]
        exact div_pos (mul_pos hcurPos hΔPos) hdenPos
      have hrearrange : boundarySynthesizedRatio s ε (k + 2) *
            (boundarySynthesizedRatio s ε (k + 2) - boundarySynthesizedRatio s ε (k + 1)) /
              (s ⟨k, hkN⟩ - boundarySynthesizedRatio s ε (k + 2)) =
          (boundarySynthesizedRatio s ε (k + 2) /
              (s ⟨k, hkN⟩ - boundarySynthesizedRatio s ε (k + 2))) *
            (boundarySynthesizedRatio s ε (k + 2) - boundarySynthesizedRatio s ε (k + 1)) := by
        ring
      have hnextLe : boundarySynthesizedRatio s ε (k + 3) -
          boundarySynthesizedRatio s ε (k + 2) ≤ ε := by
        rw [hinc, hrearrange]
        exact (mul_le_mul_of_nonneg_right hfactorLe hΔPos.le).trans (by simpa using hΔLe)
      refine ⟨hcurPos.le, by linarith, hnextPos, hnextLe, ?_⟩
      have hbound : boundarySynthesizedRatio s ε (k + 3) ≤ (k + 2 : ℝ) * ε := by
        calc
          boundarySynthesizedRatio s ε (k + 3) ≤
              boundarySynthesizedRatio s ε (k + 2) + ε := by linarith
          _ ≤ (k + 2 : ℝ) * ε := by nlinarith [hε.1]
      rw [show k + 1 + 2 = k + 3 by omega]
      norm_num only [Nat.cast_add, Nat.cast_one]
      ring_nf at hbound ⊢
      exact hbound

/-- Every denominator used by the boundary recurrence is positive. -/
theorem boundarySynthesizedRatio_denominator_pos {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) {j : ℕ} (hj : j < N) :
    0 < s ⟨j, hj⟩ - boundarySynthesizedRatio s ε (j + 2) := by
  have hinv := boundarySynthesizedRatio_invariants hε j hj.le
  have hjBound : (j + 1 : ℝ) ≤ (N + 2 : ℝ) := by
    exact_mod_cast (show j + 1 ≤ N + 2 by omega)
  have hcur := hinv.2.2.2.2.trans (mul_le_mul_of_nonneg_right hjBound hε.1.le)
  have hsmall := hε.2 ⟨j, hj⟩
  linarith

/-- The post-boundary edges realize exactly the prescribed target slopes. -/
theorem boundarySynthesizedRatio_edgeSlope {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : Fin N) :
    edgeSlope (ratioPointX (boundarySynthesizedRatio s ε))
      (ratioPointY (boundarySynthesizedRatio s ε)) (j.val + 1) = s j := by
  rw [edgeSlope, chordSlope, ratioPointX, ratioPointY]
  change
    (boundarySynthesizedRatio s ε (j.val + 2) *
          boundarySynthesizedRatio s ε (j.val + 3) -
        boundarySynthesizedRatio s ε (j.val + 1) *
          boundarySynthesizedRatio s ε (j.val + 2)) /
      (boundarySynthesizedRatio s ε (j.val + 3) -
        boundarySynthesizedRatio s ε (j.val + 2)) = s j
  have hden := boundarySynthesizedRatio_denominator_pos hε j.isLt
  have hinv := boundarySynthesizedRatio_invariants hε j.val j.isLt.le
  have hcur : boundarySynthesizedRatio s ε (j.val + 2) ≠ 0 := hinv.2.1.ne'
  have hΔ : boundarySynthesizedRatio s ε (j.val + 2) -
      boundarySynthesizedRatio s ε (j.val + 1) ≠ 0 := hinv.2.2.1.ne'
  rw [boundarySynthesizedRatio_add_three, finiteSlopeValue_apply s j.isLt]
  exact nextSynthesizedRatio_slope _ _ _ hcur hΔ hden.ne'

/-- Boundary coefficient recovery: two structural zeros followed by a positive coefficient. -/
def boundaryRecoveredCoefficient (r : ℕ → ℝ) : ℕ → ℝ
  | 0 => 0
  | 1 => 0
  | 2 => 1
  | j + 3 => boundaryRecoveredCoefficient r (j + 2) / r (j + 2)

@[simp] theorem boundaryRecoveredCoefficient_zero (r : ℕ → ℝ) :
    boundaryRecoveredCoefficient r 0 = 0 := rfl

@[simp] theorem boundaryRecoveredCoefficient_one (r : ℕ → ℝ) :
    boundaryRecoveredCoefficient r 1 = 0 := rfl

@[simp] theorem boundaryRecoveredCoefficient_two (r : ℕ → ℝ) :
    boundaryRecoveredCoefficient r 2 = 1 := rfl

@[simp] theorem boundaryRecoveredCoefficient_add_three (r : ℕ → ℝ) (j : ℕ) :
    boundaryRecoveredCoefficient r (j + 3) =
      boundaryRecoveredCoefficient r (j + 2) / r (j + 2) := rfl

/-- Positive ratios from index two onward recover positive supported coefficients. -/
theorem boundaryRecoveredCoefficient_pos {r : ℕ → ℝ} (hr : ∀ j, 2 ≤ j → 0 < r j) :
    ∀ j, 2 ≤ j → 0 < boundaryRecoveredCoefficient r j := by
  intro j hj
  induction j with
  | zero => omega
  | succ j ih =>
      rcases j with _ | _ | j
      · omega
      · simp
      · rw [show j + 2 + 1 = j + 3 by omega, boundaryRecoveredCoefficient_add_three]
        exact div_pos (ih (by omega)) (hr (j + 2) (by omega))

/-- Freeze the boundary ratio sequence after its final required value. -/
def finiteBoundaryRatio {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) (j : ℕ) : ℝ :=
  boundarySynthesizedRatio s ε (min j (N + 2))

theorem finiteBoundaryRatio_eq {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) {j : ℕ}
    (hj : j ≤ N + 2) :
    finiteBoundaryRatio s ε j = boundarySynthesizedRatio s ε j := by
  simp [finiteBoundaryRatio, min_eq_left hj]

@[simp] theorem finiteBoundaryRatio_zero {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) :
    finiteBoundaryRatio s ε 0 = 0 := by
  rw [finiteBoundaryRatio_eq s ε (by omega), boundarySynthesizedRatio_zero]

@[simp] theorem finiteBoundaryRatio_one {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) :
    finiteBoundaryRatio s ε 1 = 0 := by
  rw [finiteBoundaryRatio_eq s ε (by omega), boundarySynthesizedRatio_one]

@[simp] theorem finiteBoundaryRatio_two {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) :
    finiteBoundaryRatio s ε 2 = ε := by
  rw [finiteBoundaryRatio_eq s ε (by omega), boundarySynthesizedRatio_two]

/-- Every supported frozen boundary ratio is positive. -/
theorem finiteBoundaryRatio_pos {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : ℕ) (hj : 2 ≤ j) :
    0 < finiteBoundaryRatio s ε j := by
  let u := min j (N + 2)
  have huTwo : 2 ≤ u := by
    dsimp [u]
    exact le_min hj (by omega)
  have huBound : u ≤ N + 2 := min_le_right _ _
  let k := u - 2
  have hkN : k ≤ N := by
    dsimp [k]
    omega
  have hinv := boundarySynthesizedRatio_invariants hε k hkN
  have hku : k + 2 = u := by
    dsimp [k]
    omega
  change 0 < boundarySynthesizedRatio s ε u
  rw [← hku]
  exact hinv.2.1

/-- The frozen boundary ratios are weakly increasing. -/
theorem finiteBoundaryRatio_mono_succ {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : ℕ) :
    finiteBoundaryRatio s ε j ≤ finiteBoundaryRatio s ε (j + 1) := by
  rcases j with _ | _ | j
  · simp
  · simp [hε.1.le]
  · by_cases hj : j + 2 < N + 2
    · rw [finiteBoundaryRatio_eq s ε hj.le,
        finiteBoundaryRatio_eq s ε (by omega)]
      have hinv := boundarySynthesizedRatio_invariants hε (j + 1) (by omega)
      linarith [hinv.2.2.1]
    · have hj' : N + 2 ≤ j + 2 := Nat.le_of_not_gt hj
      simp [finiteBoundaryRatio, min_eq_right hj', min_eq_right (by omega : N + 2 ≤ j + 3)]

/-- Every prescribed post-boundary slope survives freezing. -/
theorem finiteBoundaryRatio_edgeSlope {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : Fin N) :
    edgeSlope (ratioPointX (finiteBoundaryRatio s ε))
      (ratioPointY (finiteBoundaryRatio s ε)) (j.val + 1) = s j := by
  rw [ratioPoint_edgeSlope]
  rw [finiteBoundaryRatio_eq s ε (by omega), finiteBoundaryRatio_eq s ε (by omega),
    finiteBoundaryRatio_eq s ε (by omega)]
  rw [← ratioPoint_edgeSlope (boundarySynthesizedRatio s ε) (j.val + 1)]
  exact boundarySynthesizedRatio_edgeSlope hε j

/-- The frozen boundary coefficient sequence is zero exactly in its first two positions and
positive thereafter. -/
theorem boundaryRecoveredCoefficient_nonneg {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : ℕ) :
    0 ≤ boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) j := by
  by_cases hj : 2 ≤ j
  · exact (boundaryRecoveredCoefficient_pos (finiteBoundaryRatio_pos hε) j hj).le
  · interval_cases j <;> simp

/-- Boundary coefficient recovery has the prescribed adjacent ratios from index two onward. -/
theorem boundaryRecoveredCoefficient_div_succ {r : ℕ → ℝ}
    (hr : ∀ j, 2 ≤ j → 0 < r j) (j : ℕ) :
    boundaryRecoveredCoefficient r (j + 2) /
        boundaryRecoveredCoefficient r (j + 3) = r (j + 2) := by
  rw [boundaryRecoveredCoefficient_add_three]
  have hc : boundaryRecoveredCoefficient r (j + 2) ≠ 0 :=
    (boundaryRecoveredCoefficient_pos hr (j + 2) (by omega)).ne'
  have hr0 : r (j + 2) ≠ 0 := (hr (j + 2) (by omega)).ne'
  field_simp

/-- Weak increase of the supported ratios makes the boundary coefficients log-concave. -/
theorem boundaryRecoveredCoefficient_logConcave {r : ℕ → ℝ}
    (hr : ∀ j, 2 ≤ j → 0 < r j)
    (hrMono : ∀ j, 2 ≤ j → r j ≤ r (j + 1)) (j : ℕ) :
    boundaryRecoveredCoefficient r j * boundaryRecoveredCoefficient r (j + 2) ≤
      boundaryRecoveredCoefficient r (j + 1) ^ 2 := by
  rcases j with _ | _ | j
  · simp
  · simp
  · let A := boundaryRecoveredCoefficient r (j + 3)
    let B := boundaryRecoveredCoefficient r (j + 4)
    have hA : 0 ≤ A := (boundaryRecoveredCoefficient_pos hr (j + 3) (by omega)).le
    have hB : 0 ≤ B := (boundaryRecoveredCoefficient_pos hr (j + 4) (by omega)).le
    have hleft : boundaryRecoveredCoefficient r (j + 2) = r (j + 2) * A := by
      dsimp [A]
      field_simp [(hr (j + 2) (by omega)).ne']
    have hright : A = r (j + 3) * B := by
      dsimp [A, B]
      field_simp [(hr (j + 2) (by omega)).ne', (hr (j + 3) (by omega)).ne']
    have hscaled : r (j + 2) * B ≤ r (j + 3) * B :=
      mul_le_mul_of_nonneg_right (hrMono (j + 2) (by omega)) hB
    change boundaryRecoveredCoefficient r (j + 2) * B ≤ A ^ 2
    calc
      boundaryRecoveredCoefficient r (j + 2) * B = A * (r (j + 2) * B) := by
        rw [hleft]
        ring
      _ ≤ A * (r (j + 3) * B) := mul_le_mul_of_nonneg_left hscaled hA
      _ = A ^ 2 := by rw [← hright]; ring

/-- The finite padded boundary coefficient vector for `N+2` nonloop columns. -/
def boundaryCoefficientVector {N : ℕ} (s : Fin N → ℝ) (ε : ℝ) : Fin (N + 4) → ℝ :=
  fun k ↦ boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) k.val

/-- Its positive support is exactly the interval beginning at stored coefficient index two. -/
theorem boundaryCoefficientVector_intervalSupport {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) :
    HasIntervalPositiveSupport (boundaryCoefficientVector s ε) := by
  rw [hasIntervalPositiveSupport_iff]
  intro i j k hi hj hik hkj
  have hiTwo : 2 ≤ i.val := by
    by_contra h
    have : i.val = 0 ∨ i.val = 1 := by omega
    rcases this with h | h
    · have hiEq : i = ⟨0, by omega⟩ := Fin.ext h
      rw [hiEq] at hi
      simp [boundaryCoefficientVector] at hi
    · have hiEq : i = ⟨1, by omega⟩ := Fin.ext h
      rw [hiEq] at hi
      simp [boundaryCoefficientVector] at hi
  exact boundaryRecoveredCoefficient_pos (finiteBoundaryRatio_pos hε) k.val (by omega)

/-- The finite boundary coefficient vector is discretely log-concave. -/
theorem boundaryCoefficientVector_logConcave {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) :
    DiscretelyLogConcave (n := N + 2) (boundaryCoefficientVector s ε) := by
  intro k
  simpa [boundaryCoefficientVector, pow_two, mul_comm] using
    (boundaryRecoveredCoefficient_logConcave (finiteBoundaryRatio_pos hε)
      (fun j hj ↦ finiteBoundaryRatio_mono_succ hε j) k.val)

/-- The boundary Toeplitz section is totally nonnegative through order two. -/
theorem boundaryToeplitz_tnUpTo_two {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hN : 1 ≤ N) (hε : IsAdmissibleSynthesisEpsilon s ε) :
    TNUpTo (rankThreeToeplitz (boundaryCoefficientVector s ε)) 2 := by
  rw [rankThreeToeplitz_tnUpTo_two_iff (n := N + 2) (by omega)]
  exact ⟨fun k ↦ boundaryRecoveredCoefficient_nonneg hε k.val,
    boundaryCoefficientVector_intervalSupport hε,
    boundaryCoefficientVector_logConcave hε⟩

/-- The frozen boundary coefficients and ratios satisfy the overlap equation at every index. -/
theorem boundaryCoefficient_eq_ratio_mul_succ {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : ℕ) :
    boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) j =
      finiteBoundaryRatio s ε j *
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j + 1) := by
  rcases j with _ | _ | j
  · simp
  · simp
  · have hr := finiteBoundaryRatio_pos hε (j + 2) (by omega)
    change boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j + 2) =
      finiteBoundaryRatio s ε (j + 2) *
        (boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j + 2) /
          finiteBoundaryRatio s ε (j + 2))
    field_simp [hr.ne']

/-- Consecutive supported boundary ratios increase strictly until the frozen tail. -/
theorem finiteBoundaryRatio_lt_succ {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) {j : ℕ} (hj₁ : 1 ≤ j) (hj : j < N + 2) :
    finiteBoundaryRatio s ε j < finiteBoundaryRatio s ε (j + 1) := by
  rcases j with _ | _ | j
  · omega
  · simp [hε.1]
  · rw [finiteBoundaryRatio_eq s ε (by omega),
      finiteBoundaryRatio_eq s ε (by omega)]
    have hinv := boundarySynthesizedRatio_invariants hε (j + 1) (by omega)
    linarith [hinv.2.2.1]

/-- The boundary ratio-point abscissae strictly increase before any terminal plateau is added. -/
theorem finiteBoundaryRatio_pointX_strict {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) :
    StrictlyIncreasingUpTo (ratioPointX (finiteBoundaryRatio s ε)) (N + 2) := by
  have hmono : StrictMonoOn (finiteBoundaryRatio s ε) (Set.Icc 1 (N + 2)) := by
    apply strictMonoOn_of_lt_succ Set.ordConnected_Icc
    intro j _ hjmem hsuccmem
    have hsucc := hsuccmem.2
    change j + 1 ≤ N + 2 at hsucc
    exact finiteBoundaryRatio_lt_succ hε hjmem.1 (by omega)
  intro i j hij hjN
  simp only [ratioPointX]
  exact hmono ⟨by omega, by omega⟩ ⟨by omega, by omega⟩ (by omega)

/-- The boundary ratio-point slopes are `0` followed by the prescribed positive family. -/
theorem finiteBoundaryRatio_slopesMonotone {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (hs : IsPositiveMonotoneSlopeFamily s) :
    SlopesMonotoneUpTo (ratioPointX (finiteBoundaryRatio s ε))
      (ratioPointY (finiteBoundaryRatio s ε)) (N + 2) := by
  intro i j hij hjN
  rcases i with _ | i
  · have hfirst := leftSupportBoundary_firstSlope (finiteBoundaryRatio s ε)
        (finiteBoundaryRatio_zero s ε) (finiteBoundaryRatio_one s ε)
        (by simpa using hε.1)
    by_cases hj0 : j = 0
    · subst j
      exact le_rfl
    · have hjPos : 1 ≤ j := Nat.one_le_iff_ne_zero.mpr hj0
      let q : Fin N := ⟨j - 1, by omega⟩
      have hjEq : j = q.val + 1 := by simp [q]; omega
      rw [hjEq, finiteBoundaryRatio_edgeSlope hε q]
      exact hfirst.1.le.trans (hs.1 q).le
  · have hiN : i < N := by omega
    have hjPos : 1 ≤ j := by omega
    let p : Fin N := ⟨i, hiN⟩
    let q : Fin N := ⟨j - 1, by omega⟩
    rw [show i + 1 = p.val + 1 by rfl, finiteBoundaryRatio_edgeSlope hε p]
    rw [show j = q.val + 1 by simp [q]; omega, finiteBoundaryRatio_edgeSlope hε q]
    apply hs.2
    apply Fin.mk_le_mk.mpr
    change i ≤ j - 1
    omega

/-- Each boundary Toeplitz column is a positive multiple of its affine ratio point. -/
theorem boundaryToeplitz_column {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : Fin (N + 2)) :
    (rankThreeToeplitz (boundaryCoefficientVector s ε)).col j =
      boundaryCoefficientVector s ε j.succ.succ •
        ![1, ratioPointX (finiteBoundaryRatio s ε) j.val,
          ratioPointY (finiteBoundaryRatio s ε) j.val] := by
  let r := finiteBoundaryRatio s ε
  have h₁ := boundaryCoefficient_eq_ratio_mul_succ hε (j.val + 1)
  have h₀ := boundaryCoefficient_eq_ratio_mul_succ hε j.val
  change (fun i ↦ rankThreeToeplitz (boundaryCoefficientVector s ε) i j) = _
  rw [rankThreeToeplitz_column]
  funext i
  fin_cases i
  · simp [boundaryCoefficientVector]
  · simp only [Pi.smul_apply, smul_eq_mul]
    change boundaryRecoveredCoefficient r (j.val + 1) =
      boundaryRecoveredCoefficient r (j.val + 2) * r (j.val + 1)
    nlinarith [h₁]
  · simp only [Pi.smul_apply, smul_eq_mul]
    change boundaryRecoveredCoefficient r j.val =
      boundaryRecoveredCoefficient r (j.val + 2) * (r j.val * r (j.val + 1))
    rw [h₀, h₁]
    ring

/-- Boundary maximal minors are positive scale factors times ratio-point oriented areas. -/
theorem boundaryToeplitz_minor_eq_area {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) {i j k : Fin (N + 2)}
    (hij : i < j) (hjk : j < k) :
    orderedMinor (rankThreeToeplitz (boundaryCoefficientVector s ε)) (allRows 3)
        (selectedTripleEmbedding i j k hij hjk) =
      boundaryCoefficientVector s ε i.succ.succ *
        boundaryCoefficientVector s ε j.succ.succ *
        boundaryCoefficientVector s ε k.succ.succ *
          orientedArea (ratioPointX (finiteBoundaryRatio s ε))
            (ratioPointY (finiteBoundaryRatio s ε)) i.val j.val k.val := by
  rw [orderedMinor_selectedTriple_eq_threeColumnMatrix_det,
    boundaryToeplitz_column hε, boundaryToeplitz_column hε,
    boundaryToeplitz_column hε, threeColumnMatrix_det_smul,
    ratioPoint_threeColumnMatrix_det]

/-- Every ratio-point area in the boundary chain is nonnegative. -/
theorem finiteBoundaryRatio_areasNonnegative {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (hs : IsPositiveMonotoneSlopeFamily s) :
    AreasNonnegativeUpTo (ratioPointX (finiteBoundaryRatio s ε))
      (ratioPointY (finiteBoundaryRatio s ε)) (N + 2) :=
  areasNonnegativeUpTo_of_slopesMonotoneUpTo _ _
    (finiteBoundaryRatio_pointX_strict hε)
    (finiteBoundaryRatio_slopesMonotone hε hs)

/-- All maximal minors of the boundary Toeplitz section are nonnegative. -/
theorem boundaryToeplitz_maximalMinorsNonnegative {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (hs : IsPositiveMonotoneSlopeFamily s) :
    MaximalMinorsNonnegative (rankThreeToeplitz (boundaryCoefficientVector s ε)) := by
  intro cols
  have h01 : cols 0 < cols 1 := cols.strictMono (by decide)
  have h12 : cols 1 < cols 2 := cols.strictMono (by decide)
  have harea := finiteBoundaryRatio_areasNonnegative hε hs
    (show (cols 0).val < (cols 1).val from h01)
    (show (cols 1).val < (cols 2).val from h12) (cols 2).isLt
  have hminor := boundaryToeplitz_minor_eq_area hε h01 h12
  rw [selectedTripleEmbedding_eq cols] at hminor
  rw [hminor]
  have htop : ∀ j : Fin (N + 2), 0 < boundaryCoefficientVector s ε j.succ.succ := by
    intro j
    exact boundaryRecoveredCoefficient_pos (finiteBoundaryRatio_pos hε) (j.val + 2) (by omega)
  exact mul_nonneg
    (mul_nonneg
      (mul_nonneg
        (htop (cols 0)).le (htop (cols 1)).le)
      (htop (cols 2)).le) harea

/-- The boundary Toeplitz section is totally nonnegative. -/
theorem boundaryToeplitz_totallyNonnegative {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hN : 1 ≤ N) (hε : IsAdmissibleSynthesisEpsilon s ε)
    (hs : IsPositiveMonotoneSlopeFamily s) :
    TotallyNonnegative (rankThreeToeplitz (boundaryCoefficientVector s ε)) := by
  rw [totallyNonnegative_fin_three_iff]
  exact ⟨boundaryToeplitz_tnUpTo_two hN hε,
    boundaryToeplitz_maximalMinorsNonnegative hε hs⟩

/-- The first three boundary columns give an explicit full-row-rank witness. -/
theorem boundaryToeplitz_hasFullRowRank {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hN : 1 ≤ N) :
    HasFullRowRank (rankThreeToeplitz (boundaryCoefficientVector s ε)) := by
  have hbound : 0 + 2 < N + 2 := by omega
  refine ⟨consecutiveTripleEmbedding 0 hbound, ?_⟩
  have hminor := rankThreeToeplitz_leftBoundary_minor_pos
    (a := boundaryCoefficientVector s ε) hbound (by simp [boundaryCoefficientVector])
      (by simp [boundaryCoefficientVector]) (by simp [boundaryCoefficientVector])
  exact hminor.ne'

/-- Add `ℓ` zero columns before a matrix. -/
def prependZeroColumns {m n : ℕ} (ℓ : ℕ) (B : Matrix (Fin m) (Fin n) ℝ) :
    Matrix (Fin m) (Fin (ℓ + n)) ℝ :=
  fun i j ↦ if h : j.val < ℓ then 0 else B i ⟨j.val - ℓ, by omega⟩

/-- Shift an increasing column selection past a zero prefix. -/
def shiftOrderEmbedding {k n : ℕ} (ℓ : ℕ) (cols : Fin k ↪o Fin n) :
    Fin k ↪o Fin (ℓ + n) :=
  OrderEmbedding.ofStrictMono (fun p ↦ ⟨ℓ + (cols p).val, by omega⟩) <| by
    intro i j hij
    exact Fin.mk_lt_mk.mpr (Nat.add_lt_add_left (cols.strictMono hij) ℓ)

/-- Remove a common zero-prefix shift from an increasing selection. -/
def unshiftOrderEmbedding {k n : ℕ} (ℓ : ℕ) (cols : Fin k ↪o Fin (ℓ + n))
    (hcols : ∀ p, ℓ ≤ (cols p).val) : Fin k ↪o Fin n :=
  OrderEmbedding.ofStrictMono (fun p ↦ ⟨(cols p).val - ℓ, by
    have hp := hcols p
    have hpBound := (cols p).isLt
    omega⟩) <| by
    intro i j hij
    exact Fin.mk_lt_mk.mpr (by
      have h := cols.strictMono hij
      have hi := hcols i
      omega)

/-- A minor selected entirely after the prefix equals the corresponding unshifted minor. -/
theorem orderedMinor_prependZeroColumns_unshift {m n k : ℕ} (ℓ : ℕ)
    (B : Matrix (Fin m) (Fin n) ℝ) (rows : Fin k ↪o Fin m)
    (cols : Fin k ↪o Fin (ℓ + n)) (hcols : ∀ p, ℓ ≤ (cols p).val) :
    orderedMinor (prependZeroColumns ℓ B) rows cols =
      orderedMinor B rows (unshiftOrderEmbedding ℓ cols hcols) := by
  apply congrArg Matrix.det
  ext i j
  simp only [Matrix.submatrix_apply, prependZeroColumns]
  rw [dif_neg (not_lt.mpr (hcols j))]
  rfl

/-- A minor meeting the zero prefix vanishes. -/
theorem orderedMinor_prependZeroColumns_eq_zero {m n k : ℕ} (ℓ : ℕ)
    (B : Matrix (Fin m) (Fin n) ℝ) (rows : Fin k ↪o Fin m)
    (cols : Fin k ↪o Fin (ℓ + n)) {p : Fin k} (hp : (cols p).val < ℓ) :
    orderedMinor (prependZeroColumns ℓ B) rows cols = 0 := by
  rw [orderedMinor]
  apply Matrix.det_eq_zero_of_column_eq_zero p
  intro i
  simp [prependZeroColumns, hp]

/-- Prefixing zero columns preserves total nonnegativity. -/
theorem TotallyNonnegative.prependZeroColumns {m n : ℕ} {ℓ : ℕ}
    {B : Matrix (Fin m) (Fin n) ℝ} (hB : TotallyNonnegative B) :
    TotallyNonnegative (prependZeroColumns ℓ B) := by
  intro k rows cols
  by_cases hprefix : ∃ p, (cols p).val < ℓ
  · obtain ⟨p, hp⟩ := hprefix
    exact le_of_eq (orderedMinor_prependZeroColumns_eq_zero ℓ B rows cols hp).symm
  · have hcols : ∀ p, ℓ ≤ (cols p).val := by
      intro p
      exact Nat.le_of_not_gt (not_exists.mp hprefix p)
    rw [orderedMinor_prependZeroColumns_unshift ℓ B rows cols hcols]
    exact hB.orderedMinor_nonneg rows (unshiftOrderEmbedding ℓ cols hcols)

/-- Prefixing zero columns preserves full row rank. -/
theorem HasFullRowRank.prependZeroColumns {m n : ℕ} {ℓ : ℕ}
    {B : Matrix (Fin m) (Fin n) ℝ} (hB : HasFullRowRank B) :
    HasFullRowRank (prependZeroColumns ℓ B) := by
  obtain ⟨cols, hcols⟩ := hB
  refine ⟨shiftOrderEmbedding ℓ cols, ?_⟩
  have hall : ∀ p : Fin m, ℓ ≤ ((shiftOrderEmbedding ℓ cols) p).val := by
    intro p
    simp [shiftOrderEmbedding]
  rw [orderedMinor_prependZeroColumns_unshift ℓ _ (allRows m)
    (shiftOrderEmbedding ℓ cols) hall]
  convert hcols using 1
  apply congrArg (orderedMinor B (allRows m))
  apply RelEmbedding.ext
  intro p
  apply Fin.ext
  simp [unshiftOrderEmbedding, shiftOrderEmbedding]

/-- Translate the boundary coefficient support by `ℓ`, inserting exactly `ℓ` initial loop
columns. -/
def translatedBoundaryCoefficientVector {N : ℕ} (ℓ : ℕ) (s : Fin N → ℝ) (ε : ℝ) :
    Fin ((ℓ + (N + 2)) + 2) → ℝ :=
  fun k ↦ if _h : ℓ ≤ k.val then
    boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (k.val - ℓ)
  else 0

/-- Translating the coefficient support is exactly the same as prefixing zero columns to the
boundary Toeplitz section. -/
theorem rankThreeToeplitz_translatedBoundaryCoefficientVector {N : ℕ}
    (ℓ : ℕ) (s : Fin N → ℝ) (ε : ℝ) :
    rankThreeToeplitz (translatedBoundaryCoefficientVector ℓ s ε) =
      prependZeroColumns ℓ (rankThreeToeplitz (boundaryCoefficientVector s ε)) := by
  ext i j
  fin_cases i
  · change
      (if h : ℓ ≤ j.val + 2 then
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val + 2 - ℓ) else 0) =
      if h : j.val < ℓ then 0 else
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) ((j.val - ℓ) + 2)
    by_cases hj : j.val < ℓ
    · rw [dif_pos hj]
      split_ifs with h
      · have hsmall : j.val + 2 - ℓ ≤ 1 := by omega
        interval_cases hidx : j.val + 2 - ℓ <;>
          simp
      · rfl
    · rw [dif_neg hj]
      rw [dif_pos (by omega)]
      congr 1
      omega
  · change
      (if h : ℓ ≤ j.val + 1 then
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val + 1 - ℓ) else 0) =
      if h : j.val < ℓ then 0 else
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) ((j.val - ℓ) + 1)
    by_cases hj : j.val < ℓ
    · rw [dif_pos hj]
      split_ifs with h
      · have hsmall : j.val + 1 - ℓ = 0 := by omega
        simp [hsmall]
      · rfl
    · rw [dif_neg hj]
      rw [dif_pos (by omega)]
      congr 1
      omega
  · change
      (if h : ℓ ≤ j.val then
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val - ℓ) else 0) =
      if h : j.val < ℓ then 0 else
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val - ℓ)
    by_cases hj : j.val < ℓ
    · rw [dif_pos hj]
      rw [dif_neg (by omega)]
    · rw [dif_neg hj]
      rw [dif_pos (by omega)]

/-- A translated boundary construction is totally nonnegative and full row rank. -/
theorem translatedBoundaryToeplitz_tnn_fullRowRank {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hN : 1 ≤ N) (hε : IsAdmissibleSynthesisEpsilon s ε)
    (hs : IsPositiveMonotoneSlopeFamily s) (ℓ : ℕ) :
    TotallyNonnegative (rankThreeToeplitz (translatedBoundaryCoefficientVector ℓ s ε)) ∧
      HasFullRowRank (rankThreeToeplitz (translatedBoundaryCoefficientVector ℓ s ε)) := by
  rw [rankThreeToeplitz_translatedBoundaryCoefficientVector]
  exact ⟨TotallyNonnegative.prependZeroColumns (boundaryToeplitz_totallyNonnegative hN hε hs),
    HasFullRowRank.prependZeroColumns (boundaryToeplitz_hasFullRowRank hN)⟩

/-- Reindex the column type of a finite matrix along an equality of cardinalities. -/
def castColumnCount {m n₁ n₂ : ℕ} (h : n₁ = n₂) (A : Matrix (Fin m) (Fin n₁) ℝ) :
    Matrix (Fin m) (Fin n₂) ℝ :=
  fun i j ↦ A i ⟨j.val, by omega⟩

/-- Reindex a finite coefficient vector along an equality of matrix column counts. -/
def castRankThreeCoefficients {n₁ n₂ : ℕ} (h : n₁ = n₂) (a : Fin (n₁ + 2) → ℝ) :
    Fin (n₂ + 2) → ℝ :=
  fun k ↦ a ⟨k.val, by omega⟩

/-- Casting coefficient and column counts commutes with the rank-three Toeplitz construction. -/
theorem rankThreeToeplitz_castRankThreeCoefficients {n₁ n₂ : ℕ} (h : n₁ = n₂)
    (a : Fin (n₁ + 2) → ℝ) :
    rankThreeToeplitz (castRankThreeCoefficients h a) =
      castColumnCount h (rankThreeToeplitz a) := by
  subst n₂
  rfl

/-- Cardinality casting preserves total nonnegativity. -/
theorem TotallyNonnegative.castColumnCount {m n₁ n₂ : ℕ} {h : n₁ = n₂}
    {A : Matrix (Fin m) (Fin n₁) ℝ} (hA : TotallyNonnegative A) :
    TotallyNonnegative (castColumnCount h A) := by
  subst n₂
  simpa [castColumnCount] using hA

/-- Cardinality casting preserves full row rank. -/
theorem HasFullRowRank.castColumnCount {m n₁ n₂ : ℕ} {h : n₁ = n₂}
    {A : Matrix (Fin m) (Fin n₁) ℝ} (hA : HasFullRowRank A) :
    HasFullRowRank (castColumnCount h A) := by
  subst n₂
  simpa [castColumnCount] using hA

namespace CompatibleBoundaryTargets

/-- Remove the protected first edge from the compatible target-slope family. -/
def afterLeftProtection {n : ℕ} (D : CompatibleRankThreeData n) :
    Fin (D.simplifiedSize - 2) → ℝ :=
  fun i ↦ CompatibleSlopePattern.targetSlope D ⟨i.val + 1, by omega⟩

/-- The protected-tail target slopes remain positive and weakly increasing. -/
theorem afterLeftProtection_isPositiveMonotone {n : ℕ} (D : CompatibleRankThreeData n) :
    IsPositiveMonotoneSlopeFamily (afterLeftProtection D) := by
  constructor
  · intro i
    exact CompatibleSlopePattern.targetSlope_pos D _
  · intro i j hij
    apply CompatibleSlopePattern.targetSlope_monotone D
    exact Fin.mk_le_mk.mpr (by simpa using hij)

/-- Remove both the protected first edge and the terminal vertical edge. -/
def betweenProtectedEndpoints {n : ℕ} (D : CompatibleRankThreeData n) :
    Fin (D.simplifiedSize - 3) → ℝ :=
  fun i ↦ CompatibleSlopePattern.targetSlope D ⟨i.val + 1, by omega⟩

/-- The doubly truncated targets remain positive and weakly increasing. -/
theorem betweenProtectedEndpoints_isPositiveMonotone {n : ℕ}
    (D : CompatibleRankThreeData n) :
    IsPositiveMonotoneSlopeFamily (betweenProtectedEndpoints D) := by
  constructor
  · intro i
    exact CompatibleSlopePattern.targetSlope_pos D _
  · intro i j hij
    apply CompatibleSlopePattern.targetSlope_monotone D
    exact Fin.mk_le_mk.mpr (by simpa using hij)

end CompatibleBoundaryTargets

/-- Compatible data with initial loops and a singleton terminal class have an exact-size
totally nonnegative full-rank Toeplitz realization. -/
theorem exists_leftLoop_singletonTerminal_realization {n : ℕ}
    (D : CompatibleRankThreeData n) (hleft : 0 < D.leftLoopCount)
    (hright : D.rightLoopCount = 0) (hq : D.terminalParallelSize = 1) :
    ∃ a : Fin (n + 2) → ℝ,
      TotallyNonnegative (rankThreeToeplitz a) ∧ HasFullRowRank (rankThreeToeplitz a) := by
  let s := CompatibleBoundaryTargets.afterLeftProtection D
  have hs := CompatibleBoundaryTargets.afterLeftProtection_isPositiveMonotone D
  obtain ⟨ε, hε⟩ := exists_admissibleSynthesisEpsilon hs
  have hN : 1 ≤ D.simplifiedSize - 2 := by
    have hm := D.simplifiedSize_ge_three
    omega
  have hsize : D.leftLoopCount + (D.simplifiedSize - 2 + 2) = n := by
    have hp := D.initialParallel_singleton_of_leftLoops hleft
    have hg := D.groundSize_eq
    omega
  let a₀ := translatedBoundaryCoefficientVector D.leftLoopCount s ε
  let a : Fin (n + 2) → ℝ := castRankThreeCoefficients hsize a₀
  refine ⟨a, ?_, ?_⟩
  · rw [show rankThreeToeplitz a = castColumnCount hsize (rankThreeToeplitz a₀) by
      exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
    exact TotallyNonnegative.castColumnCount
      (translatedBoundaryToeplitz_tnn_fullRowRank hN hε hs D.leftLoopCount).1
  · rw [show rankThreeToeplitz a = castColumnCount hsize (rankThreeToeplitz a₀) by
      exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
    exact HasFullRowRank.castColumnCount
      (translatedBoundaryToeplitz_tnn_fullRowRank hN hε hs D.leftLoopCount).2

/-- Every ratio point at or after the terminal cutoff is the same terminal point. -/
theorem finiteBoundaryRatio_terminalPoint_eq {N : ℕ} (s : Fin N → ℝ) (ε : ℝ)
    {j : ℕ} (hj : N + 2 ≤ j) :
    (ratioPointX (finiteBoundaryRatio s ε) j,
      ratioPointY (finiteBoundaryRatio s ε) j) =
      (boundarySynthesizedRatio s ε (N + 2),
        boundarySynthesizedRatio s ε (N + 2) ^ 2) := by
  simp only [ratioPointX, ratioPointY, finiteBoundaryRatio]
  rw [min_eq_right hj, min_eq_right (by omega : N + 2 ≤ j + 1)]
  simp [pow_two]

/-- The terminal point is vertically above the final point of the finite-slope boundary chain. -/
theorem finiteBoundaryRatio_terminalVertical {N : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) :
    ratioPointX (finiteBoundaryRatio s ε) (N + 1) =
        ratioPointX (finiteBoundaryRatio s ε) (N + 2) ∧
      ratioPointY (finiteBoundaryRatio s ε) (N + 1) <
        ratioPointY (finiteBoundaryRatio s ε) (N + 2) := by
  have hR : 0 < finiteBoundaryRatio s ε (N + 2) :=
    finiteBoundaryRatio_pos hε _ (by omega)
  have hprev : finiteBoundaryRatio s ε (N + 1) <
      finiteBoundaryRatio s ε (N + 2) :=
    finiteBoundaryRatio_lt_succ hε (by omega) (by omega)
  simp only [ratioPointX, ratioPointY]
  have hfreeze : finiteBoundaryRatio s ε (N + 3) =
      finiteBoundaryRatio s ε (N + 2) := by
    simp [finiteBoundaryRatio]
  rw [hfreeze]
  exact ⟨rfl, mul_lt_mul_of_pos_right hprev hR⟩

/-- Replacing the last vertex by a vertically higher point changes an earlier triangle area by
a nonnegative rectangular term. -/
theorem orientedArea_vertical_replace (x y : ℕ → ℝ) {i j last star : ℕ}
    (hx : x star = x last) :
    orientedArea x y i j star = orientedArea x y i j last + (x j - x i) * (y star - y last) := by
  rw [orientedArea, orientedArea, hx]
  ring_nf

/-- The frozen boundary chain, including any number of repeated terminal points, has
nonnegative oriented areas. -/
theorem finiteBoundaryRatio_extendedAreasNonnegative {N q : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε)
    (hs : IsPositiveMonotoneSlopeFamily s) :
    AreasNonnegativeUpTo (ratioPointX (finiteBoundaryRatio s ε))
      (ratioPointY (finiteBoundaryRatio s ε)) (N + 2 + q) := by
  intro i j k hij hjk hk
  by_cases hkBase : k < N + 2
  · exact finiteBoundaryRatio_areasNonnegative hε hs hij hjk hkBase
  by_cases hjTerminal : N + 2 ≤ j
  · have hjPoint := finiteBoundaryRatio_terminalPoint_eq s ε hjTerminal
    have hkPoint := finiteBoundaryRatio_terminalPoint_eq s ε (by omega : N + 2 ≤ k)
    rcases Prod.ext_iff.mp (hjPoint.trans hkPoint.symm) with ⟨hx, hy⟩
    change ratioPointX (finiteBoundaryRatio s ε) j =
      ratioPointX (finiteBoundaryRatio s ε) k at hx
    change ratioPointY (finiteBoundaryRatio s ε) j =
      ratioPointY (finiteBoundaryRatio s ε) k at hy
    rw [orientedArea, hx, hy]
    ring_nf
    exact le_rfl
  · have hjBound : j ≤ N + 1 := by omega
    have hkPoint := finiteBoundaryRatio_terminalPoint_eq s ε (by omega : N + 2 ≤ k)
    have hstarPoint := finiteBoundaryRatio_terminalPoint_eq s ε
      (show N + 2 ≤ N + 2 by omega)
    have hkEq :
        ratioPointX (finiteBoundaryRatio s ε) k =
            ratioPointX (finiteBoundaryRatio s ε) (N + 2) ∧
          ratioPointY (finiteBoundaryRatio s ε) k =
            ratioPointY (finiteBoundaryRatio s ε) (N + 2) :=
      Prod.ext_iff.mp (hkPoint.trans hstarPoint.symm)
    rw [orientedArea]
    rw [hkEq.1, hkEq.2]
    rw [← orientedArea]
    by_cases hjLast : j = N + 1
    · subst j
      have hvertical := finiteBoundaryRatio_terminalVertical hε
      rw [orientedArea, hvertical.1]
      have hxPos : 0 < ratioPointX (finiteBoundaryRatio s ε) (N + 1) -
          ratioPointX (finiteBoundaryRatio s ε) i :=
        sub_pos.mpr (finiteBoundaryRatio_pointX_strict hε hij (by omega))
      have hprod := mul_pos hxPos (sub_pos.mpr hvertical.2)
      nlinarith
    · have hjStrict : j < N + 1 := by omega
      rw [orientedArea_vertical_replace _ _
        (finiteBoundaryRatio_terminalVertical hε).1.symm]
      have hbase := finiteBoundaryRatio_areasNonnegative hε hs hij hjStrict (by omega)
      have hxNonneg : 0 ≤ ratioPointX (finiteBoundaryRatio s ε) j -
          ratioPointX (finiteBoundaryRatio s ε) i :=
        (sub_pos.mpr (finiteBoundaryRatio_pointX_strict hε hij (by omega))).le
      have hyNonneg : 0 ≤ ratioPointY (finiteBoundaryRatio s ε) (N + 2) -
          ratioPointY (finiteBoundaryRatio s ε) (N + 1) :=
        (sub_pos.mpr (finiteBoundaryRatio_terminalVertical hε).2).le
      exact add_nonneg hbase (mul_nonneg hxNonneg hyNonneg)

/-- Extend the boundary coefficient vector through `q` raw terminal-class columns. -/
def boundaryCoefficientVectorExtra {N : ℕ} (q : ℕ) (s : Fin N → ℝ) (ε : ℝ) :
    Fin ((N + 2 + q) + 2) → ℝ :=
  fun k ↦ boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) k.val

/-- The extended vector remains `TN₂`. -/
theorem boundaryToeplitzExtra_tnUpTo_two {N q : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hsize : 3 ≤ N + 2 + q) (hε : IsAdmissibleSynthesisEpsilon s ε) :
    TNUpTo (rankThreeToeplitz (boundaryCoefficientVectorExtra q s ε)) 2 := by
  rw [rankThreeToeplitz_tnUpTo_two_iff hsize]
  refine ⟨fun k ↦ boundaryRecoveredCoefficient_nonneg hε k.val, ?_, ?_⟩
  · rw [hasIntervalPositiveSupport_iff]
    intro i j k hi hj hik hkj
    have hiTwo : 2 ≤ i.val := by
      by_contra h
      have hiSmall : i.val = 0 ∨ i.val = 1 := by omega
      rcases hiSmall with hi0 | hi1
      · have hiEq : i = ⟨0, by omega⟩ := Fin.ext hi0
        rw [hiEq] at hi
        simp [boundaryCoefficientVectorExtra] at hi
      · have hiEq : i = ⟨1, by omega⟩ := Fin.ext hi1
        rw [hiEq] at hi
        simp [boundaryCoefficientVectorExtra] at hi
    exact boundaryRecoveredCoefficient_pos (finiteBoundaryRatio_pos hε) k.val (by omega)
  · intro k
    simpa [boundaryCoefficientVectorExtra, pow_two, mul_comm] using
      (boundaryRecoveredCoefficient_logConcave (finiteBoundaryRatio_pos hε)
        (fun j hj ↦ finiteBoundaryRatio_mono_succ hε j) k.val)

/-- Extended boundary columns have the same positive ratio-point normalization. -/
theorem boundaryToeplitzExtra_column {N q : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) (j : Fin (N + 2 + q)) :
    (rankThreeToeplitz (boundaryCoefficientVectorExtra q s ε)).col j =
      boundaryCoefficientVectorExtra q s ε j.succ.succ •
        ![1, ratioPointX (finiteBoundaryRatio s ε) j.val,
          ratioPointY (finiteBoundaryRatio s ε) j.val] := by
  let r := finiteBoundaryRatio s ε
  have h₁ := boundaryCoefficient_eq_ratio_mul_succ hε (j.val + 1)
  have h₀ := boundaryCoefficient_eq_ratio_mul_succ hε j.val
  change (fun i ↦ rankThreeToeplitz (boundaryCoefficientVectorExtra q s ε) i j) = _
  rw [rankThreeToeplitz_column]
  funext i
  fin_cases i
  · simp [boundaryCoefficientVectorExtra]
  · simp only [Pi.smul_apply, smul_eq_mul]
    change boundaryRecoveredCoefficient r (j.val + 1) =
      boundaryRecoveredCoefficient r (j.val + 2) * r (j.val + 1)
    nlinarith [h₁]
  · simp only [Pi.smul_apply, smul_eq_mul]
    change boundaryRecoveredCoefficient r j.val =
      boundaryRecoveredCoefficient r (j.val + 2) * (r j.val * r (j.val + 1))
    rw [h₀, h₁]
    ring

/-- Extended maximal minors are scale factors times extended ratio-chain areas. -/
theorem boundaryToeplitzExtra_minor_eq_area {N q : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hε : IsAdmissibleSynthesisEpsilon s ε) {i j k : Fin (N + 2 + q)}
    (hij : i < j) (hjk : j < k) :
    orderedMinor (rankThreeToeplitz (boundaryCoefficientVectorExtra q s ε)) (allRows 3)
        (selectedTripleEmbedding i j k hij hjk) =
      boundaryCoefficientVectorExtra q s ε i.succ.succ *
        boundaryCoefficientVectorExtra q s ε j.succ.succ *
        boundaryCoefficientVectorExtra q s ε k.succ.succ *
          orientedArea (ratioPointX (finiteBoundaryRatio s ε))
            (ratioPointY (finiteBoundaryRatio s ε)) i.val j.val k.val := by
  rw [orderedMinor_selectedTriple_eq_threeColumnMatrix_det,
    boundaryToeplitzExtra_column hε, boundaryToeplitzExtra_column hε,
    boundaryToeplitzExtra_column hε, threeColumnMatrix_det_smul,
    ratioPoint_threeColumnMatrix_det]

/-- The extended boundary Toeplitz section is totally nonnegative. -/
theorem boundaryToeplitzExtra_totallyNonnegative {N q : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hsize : 3 ≤ N + 2 + q) (hε : IsAdmissibleSynthesisEpsilon s ε)
    (hs : IsPositiveMonotoneSlopeFamily s) :
    TotallyNonnegative (rankThreeToeplitz (boundaryCoefficientVectorExtra q s ε)) := by
  rw [totallyNonnegative_fin_three_iff]
  refine ⟨boundaryToeplitzExtra_tnUpTo_two hsize hε, ?_⟩
  intro cols
  have h01 : cols 0 < cols 1 := cols.strictMono (by decide)
  have h12 : cols 1 < cols 2 := cols.strictMono (by decide)
  have harea := finiteBoundaryRatio_extendedAreasNonnegative (q := q) hε hs
    (show (cols 0).val < (cols 1).val from h01)
    (show (cols 1).val < (cols 2).val from h12) (cols 2).isLt
  have hminor := boundaryToeplitzExtra_minor_eq_area hε h01 h12
  rw [selectedTripleEmbedding_eq cols] at hminor
  rw [hminor]
  have htop : ∀ j : Fin (N + 2 + q),
      0 < boundaryCoefficientVectorExtra q s ε j.succ.succ := by
    intro j
    exact boundaryRecoveredCoefficient_pos (finiteBoundaryRatio_pos hε) (j.val + 2) (by omega)
  exact mul_nonneg (mul_nonneg (mul_nonneg (htop (cols 0)).le (htop (cols 1)).le)
    (htop (cols 2)).le) harea

/-- The extended boundary section remains full row rank. -/
theorem boundaryToeplitzExtra_hasFullRowRank {N q : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hsize : 3 ≤ N + 2 + q) :
    HasFullRowRank (rankThreeToeplitz (boundaryCoefficientVectorExtra q s ε)) := by
  have hbound : 0 + 2 < N + 2 + q := by omega
  refine ⟨consecutiveTripleEmbedding 0 hbound, ?_⟩
  have hminor := rankThreeToeplitz_leftBoundary_minor_pos
    (a := boundaryCoefficientVectorExtra q s ε) hbound
      (by simp [boundaryCoefficientVectorExtra])
      (by simp [boundaryCoefficientVectorExtra])
      (by simp [boundaryCoefficientVectorExtra])
  exact hminor.ne'

/-- Translate an extended terminal-class boundary construction past `ℓ` initial loops. -/
def translatedBoundaryExtraCoefficientVector {N : ℕ} (ℓ q : ℕ) (s : Fin N → ℝ) (ε : ℝ) :
    Fin ((ℓ + (N + 2 + q)) + 2) → ℝ :=
  fun k ↦ if _h : ℓ ≤ k.val then
    boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (k.val - ℓ)
  else 0

/-- The translated extended construction is a zero-column prefix of the extended boundary
matrix. -/
theorem rankThreeToeplitz_translatedBoundaryExtraCoefficientVector {N : ℕ}
    (ℓ q : ℕ) (s : Fin N → ℝ) (ε : ℝ) :
    rankThreeToeplitz (translatedBoundaryExtraCoefficientVector ℓ q s ε) =
      prependZeroColumns ℓ (rankThreeToeplitz (boundaryCoefficientVectorExtra q s ε)) := by
  ext i j
  fin_cases i
  · change
      (if h : ℓ ≤ j.val + 2 then
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val + 2 - ℓ) else 0) =
      if h : j.val < ℓ then 0 else
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) ((j.val - ℓ) + 2)
    by_cases hj : j.val < ℓ
    · rw [dif_pos hj]
      split_ifs
      · have hsmall : j.val + 2 - ℓ ≤ 1 := by omega
        interval_cases j.val + 2 - ℓ <;> simp
      · rfl
    · rw [dif_neg hj, dif_pos (by omega)]
      congr 1
      omega
  · change
      (if h : ℓ ≤ j.val + 1 then
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val + 1 - ℓ) else 0) =
      if h : j.val < ℓ then 0 else
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) ((j.val - ℓ) + 1)
    by_cases hj : j.val < ℓ
    · rw [dif_pos hj]
      split_ifs
      · have hsmall : j.val + 1 - ℓ = 0 := by omega
        simp [hsmall]
      · rfl
    · rw [dif_neg hj, dif_pos (by omega)]
      congr 1
      omega
  · change
      (if h : ℓ ≤ j.val then
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val - ℓ) else 0) =
      if h : j.val < ℓ then 0 else
        boundaryRecoveredCoefficient (finiteBoundaryRatio s ε) (j.val - ℓ)
    by_cases hj : j.val < ℓ
    · rw [dif_pos hj, dif_neg (by omega)]
    · rw [dif_neg hj, dif_pos (by omega)]

/-- Translation preserves TNN and full rank for the extended terminal-class construction. -/
theorem translatedBoundaryExtra_tnn_fullRowRank {N q : ℕ} {s : Fin N → ℝ} {ε : ℝ}
    (hsize : 3 ≤ N + 2 + q) (hε : IsAdmissibleSynthesisEpsilon s ε)
    (hs : IsPositiveMonotoneSlopeFamily s) (ℓ : ℕ) :
    TotallyNonnegative
        (rankThreeToeplitz (translatedBoundaryExtraCoefficientVector ℓ q s ε)) ∧
      HasFullRowRank
        (rankThreeToeplitz (translatedBoundaryExtraCoefficientVector ℓ q s ε)) := by
  rw [rankThreeToeplitz_translatedBoundaryExtraCoefficientVector]
  exact ⟨TotallyNonnegative.prependZeroColumns
      (boundaryToeplitzExtra_totallyNonnegative hsize hε hs),
    HasFullRowRank.prependZeroColumns (boundaryToeplitzExtra_hasFullRowRank hsize)⟩

/-- Compatible data with initial loops and a nontrivial terminal class have an exact-size
totally nonnegative full-rank Toeplitz realization. -/
theorem exists_leftLoop_nonsingletonTerminal_realization {n : ℕ}
    (D : CompatibleRankThreeData n) (hleft : 0 < D.leftLoopCount)
    (hright : D.rightLoopCount = 0) (hq : 1 < D.terminalParallelSize) :
    ∃ a : Fin (n + 2) → ℝ,
      TotallyNonnegative (rankThreeToeplitz a) ∧ HasFullRowRank (rankThreeToeplitz a) := by
  let s := CompatibleBoundaryTargets.betweenProtectedEndpoints D
  have hs := CompatibleBoundaryTargets.betweenProtectedEndpoints_isPositiveMonotone D
  obtain ⟨ε, hε⟩ := exists_admissibleSynthesisEpsilon hs
  have hmatrixSize : 3 ≤ (D.simplifiedSize - 3) + 2 + D.terminalParallelSize := by
    have hm := D.simplifiedSize_ge_three
    omega
  have hsize : D.leftLoopCount +
      ((D.simplifiedSize - 3) + 2 + D.terminalParallelSize) = n := by
    have hp := D.initialParallel_singleton_of_leftLoops hleft
    have hg := D.groundSize_eq
    have hm := D.simplifiedSize_ge_three
    omega
  let a₀ := translatedBoundaryExtraCoefficientVector D.leftLoopCount
    D.terminalParallelSize s ε
  let a : Fin (n + 2) → ℝ := castRankThreeCoefficients hsize a₀
  refine ⟨a, ?_, ?_⟩
  · rw [show rankThreeToeplitz a = castColumnCount hsize (rankThreeToeplitz a₀) by
      exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
    exact TotallyNonnegative.castColumnCount
      (translatedBoundaryExtra_tnn_fullRowRank hmatrixSize hε hs D.leftLoopCount).1
  · rw [show rankThreeToeplitz a = castColumnCount hsize (rankThreeToeplitz a₀) by
      exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
    exact HasFullRowRank.castColumnCount
      (translatedBoundaryExtra_tnn_fullRowRank hmatrixSize hε hs D.leftLoopCount).2

/-- Every compatible datum with a nonempty initial loop block and no terminal loops has a TNN
full-row-rank Toeplitz realization, for either terminal-class size. -/
theorem exists_leftLoop_realization {n : ℕ} (D : CompatibleRankThreeData n)
    (hleft : 0 < D.leftLoopCount) (hright : D.rightLoopCount = 0) :
    ∃ a : Fin (n + 2) → ℝ,
      TotallyNonnegative (rankThreeToeplitz a) ∧ HasFullRowRank (rankThreeToeplitz a) := by
  have hqle : 1 ≤ D.terminalParallelSize := D.terminalParallelSize_pos
  rcases hqle.eq_or_lt with hq | hq
  · exact exists_leftLoop_singletonTerminal_realization D hleft hright hq.symm
  · exact exists_leftLoop_nonsingletonTerminal_realization D hleft hright hq

/-- A canonical strictly increasing positive slope family of any finite length. -/
def indexSlope (N : ℕ) : Fin N → ℝ :=
  fun i ↦ i.val + 1

theorem indexSlope_isPositiveMonotone (N : ℕ) :
    IsPositiveMonotoneSlopeFamily (indexSlope N) := by
  constructor
  · intro i
    change (0 : ℝ) < (i.val : ℝ) + 1
    exact add_pos_of_nonneg_of_pos (Nat.cast_nonneg _) zero_lt_one
  · intro i j hij
    dsimp [indexSlope]
    have hval : (i.val : ℝ) ≤ (j.val : ℝ) := by
      exact_mod_cast (show i.val ≤ j.val from hij)
    linarith

/-- A right-loop datum can be constructed from a left-boundary model with reversed endpoint
class sizes, then reversed in both matrix axes. -/
theorem exists_rightLoop_realization {n : ℕ} (D : CompatibleRankThreeData n)
    (hleft : D.leftLoopCount = 0) (hright : 0 < D.rightLoopCount) :
    ∃ a : Fin (n + 2) → ℝ,
      TotallyNonnegative (rankThreeToeplitz a) ∧ HasFullRowRank (rankThreeToeplitz a) := by
  have hqOriginal := D.terminalParallel_singleton_of_rightLoops hright
  have hpPos : 1 ≤ D.initialParallelSize := D.initialParallelSize_pos
  rcases hpPos.eq_or_lt with hp | hp
  · let s := indexSlope (D.simplifiedSize - 2)
    have hs := indexSlope_isPositiveMonotone (D.simplifiedSize - 2)
    obtain ⟨ε, hε⟩ := exists_admissibleSynthesisEpsilon hs
    have hN : 1 ≤ D.simplifiedSize - 2 := by
      have hm := D.simplifiedSize_ge_three
      omega
    have hsize : D.rightLoopCount + (D.simplifiedSize - 2 + 2) = n := by
      have hg := D.groundSize_eq
      have hm := D.simplifiedSize_ge_three
      omega
    let a₀ := translatedBoundaryCoefficientVector D.rightLoopCount s ε
    let aLeft : Fin (n + 2) → ℝ := castRankThreeCoefficients hsize a₀
    have hleftModel : TotallyNonnegative (rankThreeToeplitz aLeft) ∧
        HasFullRowRank (rankThreeToeplitz aLeft) := by
      constructor
      · rw [show rankThreeToeplitz aLeft = castColumnCount hsize (rankThreeToeplitz a₀) by
          exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
        exact TotallyNonnegative.castColumnCount
          (translatedBoundaryToeplitz_tnn_fullRowRank hN hε hs D.rightLoopCount).1
      · rw [show rankThreeToeplitz aLeft = castColumnCount hsize (rankThreeToeplitz a₀) by
          exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
        exact HasFullRowRank.castColumnCount
          (translatedBoundaryToeplitz_tnn_fullRowRank hN hε hs D.rightLoopCount).2
    let a : Fin (n + 2) → ℝ := aLeft ∘ Fin.rev
    refine ⟨a, ?_, ?_⟩
    · rw [show rankThreeToeplitz a = reverseMatrix (rankThreeToeplitz aLeft) by
        simpa [a, reverseMatrix] using (rankThreeToeplitz_submatrix_rev aLeft).symm]
      exact hleftModel.1.reverseMatrix
    · rw [show rankThreeToeplitz a = reverseMatrix (rankThreeToeplitz aLeft) by
        simpa [a, reverseMatrix] using (rankThreeToeplitz_submatrix_rev aLeft).symm]
      exact (hasFullRowRank_reverseMatrix_iff _).2 hleftModel.2
  · let s := indexSlope (D.simplifiedSize - 3)
    have hs := indexSlope_isPositiveMonotone (D.simplifiedSize - 3)
    obtain ⟨ε, hε⟩ := exists_admissibleSynthesisEpsilon hs
    have hmatrixSize : 3 ≤ (D.simplifiedSize - 3) + 2 + D.initialParallelSize := by
      have hm := D.simplifiedSize_ge_three
      omega
    have hsize : D.rightLoopCount +
        ((D.simplifiedSize - 3) + 2 + D.initialParallelSize) = n := by
      have hg := D.groundSize_eq
      have hm := D.simplifiedSize_ge_three
      omega
    let a₀ := translatedBoundaryExtraCoefficientVector D.rightLoopCount
      D.initialParallelSize s ε
    let aLeft : Fin (n + 2) → ℝ := castRankThreeCoefficients hsize a₀
    have hleftModel : TotallyNonnegative (rankThreeToeplitz aLeft) ∧
        HasFullRowRank (rankThreeToeplitz aLeft) := by
      constructor
      · rw [show rankThreeToeplitz aLeft = castColumnCount hsize (rankThreeToeplitz a₀) by
          exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
        exact TotallyNonnegative.castColumnCount
          (translatedBoundaryExtra_tnn_fullRowRank hmatrixSize hε hs D.rightLoopCount).1
      · rw [show rankThreeToeplitz aLeft = castColumnCount hsize (rankThreeToeplitz a₀) by
          exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
        exact HasFullRowRank.castColumnCount
          (translatedBoundaryExtra_tnn_fullRowRank hmatrixSize hε hs D.rightLoopCount).2
    let a : Fin (n + 2) → ℝ := aLeft ∘ Fin.rev
    refine ⟨a, ?_, ?_⟩
    · rw [show rankThreeToeplitz a = reverseMatrix (rankThreeToeplitz aLeft) by
        simpa [a, reverseMatrix] using (rankThreeToeplitz_submatrix_rev aLeft).symm]
      exact hleftModel.1.reverseMatrix
    · rw [show rankThreeToeplitz a = reverseMatrix (rankThreeToeplitz aLeft) by
        simpa [a, reverseMatrix] using (rankThreeToeplitz_submatrix_rev aLeft).symm]
      exact (hasFullRowRank_reverseMatrix_iff _).2 hleftModel.2

/-- In the absence of loop boundaries, a positive strictly convex Toeplitz section of the exact
raw size supplies a TNN full-rank realization. -/
theorem exists_noLoop_tnn_fullRowRank {n : ℕ} (D : CompatibleRankThreeData n)
    (hleft : D.leftLoopCount = 0) (hright : D.rightLoopCount = 0) :
    ∃ a : Fin (n + 2) → ℝ,
      TotallyNonnegative (rankThreeToeplitz a) ∧ HasFullRowRank (rankThreeToeplitz a) := by
  have hn : 3 ≤ n := by
    have hg := D.groundSize_eq
    have hm := D.simplifiedSize_ge_three
    have hp := D.initialParallelSize_pos
    have hq := D.terminalParallelSize_pos
    omega
  let s := indexSlope (n - 1)
  have hs := indexSlope_isPositiveMonotone (n - 1)
  obtain ⟨ε, hε⟩ := exists_admissibleSynthesisEpsilon hs
  have hN : 2 ≤ n - 1 := by omega
  have hsize : (n - 1) + 1 = n := by omega
  let a₀ := synthesizedCoefficientVector s ε
  let a : Fin (n + 2) → ℝ := castRankThreeCoefficients hsize a₀
  have htnn₀ := synthesizedToeplitz_totallyNonnegative hN hε hs.2
  have ht : 0 + 1 < n - 1 := by omega
  have hstrict : s ⟨0, by omega⟩ < s ⟨1, ht⟩ := by
    norm_num [s, indexSlope]
  have hrank₀ := synthesizedToeplitz_hasFullRowRank_of_strictSlope hε ht hstrict
  refine ⟨a, ?_, ?_⟩
  · rw [show rankThreeToeplitz a = castColumnCount hsize (rankThreeToeplitz a₀) by
      exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
    exact TotallyNonnegative.castColumnCount htnn₀
  · rw [show rankThreeToeplitz a = castColumnCount hsize (rankThreeToeplitz a₀) by
      exact rankThreeToeplitz_castRankThreeCoefficients hsize a₀]
    exact HasFullRowRank.castColumnCount hrank₀

/-- Every compatible datum with at most one nonempty loop boundary admits an exact-size TNN
full-row-rank Toeplitz matrix. -/
theorem exists_oneSided_tnn_fullRowRank {n : ℕ} (D : CompatibleRankThreeData n)
    (honeSide : D.leftLoopCount = 0 ∨ D.rightLoopCount = 0) :
    ∃ a : Fin (n + 2) → ℝ,
      TotallyNonnegative (rankThreeToeplitz a) ∧ HasFullRowRank (rankThreeToeplitz a) := by
  rcases honeSide with hleft | hright
  · by_cases hrightPos : 0 < D.rightLoopCount
    · exact exists_rightLoop_realization D hleft hrightPos
    · have hrightZero : D.rightLoopCount = 0 := Nat.eq_zero_of_not_pos hrightPos
      exact exists_noLoop_tnn_fullRowRank D hleft hrightZero
  · by_cases hleftPos : 0 < D.leftLoopCount
    · exact exists_leftLoop_realization D hleftPos hright
    · have hleftZero : D.leftLoopCount = 0 := Nat.eq_zero_of_not_pos hleftPos
      exact exists_noLoop_tnn_fullRowRank D hleftZero hright

end

end ToeplitzPositroids.RankThree
